<?xml version="1.0" encoding="utf-8"?><Database Name="school" Class="UserDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=school;Integrated Security=True;Connect Timeout=30" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="schoolConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Profile" Member="Profiles">
    <Type Name="Profile">
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Profile_Message" Member="Messages" ThisKey="Username" OtherKey="Reciever" Type="Message" />
      <Association Name="Profile_Message1" Member="Messages1" ThisKey="Username" OtherKey="Sender" Type="Message" />
    </Type>
  </Table>
  <Table Name="dbo.Message" Member="Messages">
    <Type Name="Message">
      <Column Name="MessageId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Reciever" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Time" Type="System.Data.Linq.Binary" DbType="rowversion" CanBeNull="true" IsVersion="true" />
      <Column Name="Message" Member="Message1" Type="System.String" DbType="NText" CanBeNull="true" />
      <Association Name="Profile_Message" Member="Profile" ThisKey="Reciever" OtherKey="Username" Type="Profile" IsForeignKey="true" />
      <Association Name="Profile_Message1" Member="Profile1" ThisKey="Sender" OtherKey="Username" Type="Profile" IsForeignKey="true" />
    </Type>
  </Table>
</Database>